function psi = generate_coherent_vector(alpha, maxPhoton)
% Creates coherent state
%   psi = generate_coherent_vector(alpha, maxPhoton) returns the pure state
%   vector in the photon number basis of complex amplutude alpha. maxPhoton
%   is the photon number at which the Hilbert space is truncated.

n = (0:maxPhoton).';
psi = alpha.^n./sqrt(factorial(n));
normalization = exp(-0.5 .* abs(alpha).^2);
psi = normalization * psi;

psi = normalize(psi,'check');

% TODO: allow maxPhoton to be generated by init_tables
% TODO: option to output density matrix